<?php

use App\Models\Idea\Country;
use Illuminate\Database\Seeder;
use App\Models\Idea\CountryTranslation;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('countries')->truncate();
        $countries = [
            array('id' => '1', 'code' => 'AF'),
            array('id' => '2', 'code' => 'AL'),
            array('id' => '3', 'code' => 'DZ'),
            array('id' => '4', 'code' => 'DS'),
            array('id' => '5', 'code' => 'AD'),
            array('id' => '6', 'code' => 'AO'),
            array('id' => '7', 'code' => 'AI'),
            array('id' => '8', 'code' => 'AQ'),
            array('id' => '9', 'code' => 'AG'),
            array('id' => '10', 'code' => 'AR'),
            array('id' => '11', 'code' => 'AM'),
            array('id' => '12', 'code' => 'AW'),
            array('id' => '13', 'code' => 'AU'),
            array('id' => '14', 'code' => 'AT'),
            array('id' => '15', 'code' => 'AZ'),
            array('id' => '16', 'code' => 'BS'),
            array('id' => '17', 'code' => 'BH'),
            array('id' => '18', 'code' => 'BD'),
            array('id' => '19', 'code' => 'BB'),
            array('id' => '20', 'code' => 'BY'),
            array('id' => '21', 'code' => 'BE'),
            array('id' => '22', 'code' => 'BZ'),
            array('id' => '23', 'code' => 'BJ'),
            array('id' => '24', 'code' => 'BM'),
            array('id' => '25', 'code' => 'BT'),
            array('id' => '26', 'code' => 'BO'),
            array('id' => '27', 'code' => 'BA'),
            array('id' => '28', 'code' => 'BW'),
            array('id' => '29', 'code' => 'BV'),
            array('id' => '31', 'code' => 'BR'),
            array('id' => '32', 'code' => 'IO'),
            array('id' => '33', 'code' => 'BN'),
            array('id' => '34', 'code' => 'BG'),
            array('id' => '35', 'code' => 'BF'),
            array('id' => '36', 'code' => 'BI'),
            array('id' => '37', 'code' => 'KH'),
            array('id' => '38', 'code' => 'CM'),
            array('id' => '39', 'code' => 'CA'),
            array('id' => '40', 'code' => 'CV'),
            array('id' => '41', 'code' => 'KY'),
            array('id' => '42', 'code' => 'CF'),
            array('id' => '43', 'code' => 'TD'),
            array('id' => '44', 'code' => 'CL'),
            array('id' => '45', 'code' => 'CN'),
            array('id' => '46', 'code' => 'CX'),
            array('id' => '47', 'code' => 'CC'),
            array('id' => '48', 'code' => 'CO'),
            array('id' => '49', 'code' => 'KM'),
            array('id' => '50', 'code' => 'CG'),
            array('id' => '51', 'code' => 'CK'),
            array('id' => '52', 'code' => 'CR'),
            array('id' => '53', 'code' => 'HR'),
            array('id' => '54', 'code' => 'CU'),
            array('id' => '55', 'code' => 'CY'),
            array('id' => '56', 'code' => 'CZ'),
            array('id' => '57', 'code' => 'DK'),
            array('id' => '58', 'code' => 'DJ'),
            array('id' => '59', 'code' => 'DM'),
            array('id' => '60', 'code' => 'DO'),
            array('id' => '61', 'code' => 'TP'),
            array('id' => '62', 'code' => 'EC'),
            array('id' => '63', 'code' => 'EG'),
            array('id' => '64', 'code' => 'SV'),
            array('id' => '65', 'code' => 'GQ'),
            array('id' => '66', 'code' => 'ER'),
            array('id' => '67', 'code' => 'EE'),
            array('id' => '68', 'code' => 'ET'),
            array('id' => '69', 'code' => 'FK'),
            array('id' => '70', 'code' => 'FO'),
            array('id' => '71', 'code' => 'FJ'),
            array('id' => '72', 'code' => 'FI'),
            array('id' => '73', 'code' => 'FR'),
            array('id' => '74', 'code' => 'GF'),
            array('id' => '75', 'code' => 'PF'),
            array('id' => '76', 'code' => 'TF'),
            array('id' => '77', 'code' => 'GA'),
            array('id' => '78', 'code' => 'GM'),
            array('id' => '79', 'code' => 'GE'),
            array('id' => '80', 'code' => 'DE'),
            array('id' => '81', 'code' => 'GH'),
            array('id' => '82', 'code' => 'GI'),
            array('id' => '83', 'code' => 'GK'),
            array('id' => '84', 'code' => 'GR'),
            array('id' => '85', 'code' => 'GL'),
            array('id' => '86', 'code' => 'GD'),
            array('id' => '87', 'code' => 'GP'),
            array('id' => '88', 'code' => 'GU'),
            array('id' => '89', 'code' => 'GT'),
            array('id' => '90', 'code' => 'GN'),
            array('id' => '91', 'code' => 'GW'),
            array('id' => '92', 'code' => 'GY'),
            array('id' => '93', 'code' => 'HT'),
            array('id' => '94', 'code' => 'HM'),
            array('id' => '95', 'code' => 'HN'),
            array('id' => '96', 'code' => 'HK'),
            array('id' => '97', 'code' => 'HU'),
            array('id' => '98', 'code' => 'IS'),
            array('id' => '99', 'code' => 'IN'),
            array('id' => '100', 'code' => 'IM'),
            array('id' => '101', 'code' => 'ID'),
            array('id' => '102', 'code' => 'IR'),
            array('id' => '103', 'code' => 'IQ'),
            array('id' => '104', 'code' => 'IE'),
            array('id' => '105', 'code' => 'IL'),
            array('id' => '106', 'code' => 'IT'),
            array('id' => '107', 'code' => 'CI'),
            array('id' => '108', 'code' => 'JE'),
            array('id' => '109', 'code' => 'JM'),
            array('id' => '110', 'code' => 'JP'),
            array('id' => '111', 'code' => 'JO'),
            array('id' => '112', 'code' => 'KZ'),
            array('id' => '113', 'code' => 'KE'),
            array('id' => '114', 'code' => 'KI'),
            array('id' => '115', 'code' => 'KP'),
            array('id' => '116', 'code' => 'KR'),
            array('id' => '117', 'code' => 'XK'),
            array('id' => '118', 'code' => 'KW'),
            array('id' => '119', 'code' => 'KG'),
            array('id' => '120', 'code' => 'LA'),
            array('id' => '121', 'code' => 'LV'),
            array('id' => '122', 'code' => 'LB'),
            array('id' => '123', 'code' => 'LS'),
            array('id' => '124', 'code' => 'LR'),
            array('id' => '125', 'code' => 'LY'),
            array('id' => '126', 'code' => 'LI'),
            array('id' => '127', 'code' => 'LT'),
            array('id' => '128', 'code' => 'LU'),
            array('id' => '129', 'code' => 'MO'),
            array('id' => '130', 'code' => 'MK'),
            array('id' => '131', 'code' => 'MG'),
            array('id' => '132', 'code' => 'MW'),
            array('id' => '133', 'code' => 'MY'),
            array('id' => '134', 'code' => 'MV'),
            array('id' => '135', 'code' => 'ML'),
            array('id' => '136', 'code' => 'MT'),
            array('id' => '137', 'code' => 'MH'),
            array('id' => '138', 'code' => 'MQ'),
            array('id' => '139', 'code' => 'MR'),
            array('id' => '140', 'code' => 'MU'),
            array('id' => '141', 'code' => 'TY'),
            array('id' => '142', 'code' => 'MX'),
            array('id' => '143', 'code' => 'FM'),
            array('id' => '144', 'code' => 'MD'),
            array('id' => '145', 'code' => 'MC'),
            array('id' => '146', 'code' => 'MN'),
            array('id' => '147', 'code' => 'ME'),
            array('id' => '148', 'code' => 'MS'),
            array('id' => '149', 'code' => 'MA'),
            array('id' => '150', 'code' => 'MZ'),
            array('id' => '151', 'code' => 'MM'),
            array('id' => '152', 'code' => 'NA'),
            array('id' => '153', 'code' => 'NR'),
            array('id' => '154', 'code' => 'NP'),
            array('id' => '155', 'code' => 'NL'),
            array('id' => '156', 'code' => 'AN'),
            array('id' => '157', 'code' => 'NC'),
            array('id' => '158', 'code' => 'NZ'),
            array('id' => '159', 'code' => 'NI'),
            array('id' => '160', 'code' => 'NE'),
            array('id' => '161', 'code' => 'NG'),
            array('id' => '162', 'code' => 'NU'),
            array('id' => '163', 'code' => 'NF'),
            array('id' => '164', 'code' => 'MP'),
            array('id' => '165', 'code' => 'NO'),
            array('id' => '166', 'code' => 'OM'),
            array('id' => '167', 'code' => 'PK'),
            array('id' => '168', 'code' => 'PW'),
            array('id' => '169', 'code' => 'PS'),
            array('id' => '170', 'code' => 'PA'),
            array('id' => '171', 'code' => 'PG'),
            array('id' => '172', 'code' => 'PY'),
            array('id' => '173', 'code' => 'PE'),
            array('id' => '174', 'code' => 'PH'),
            array('id' => '175', 'code' => 'PN'),
            array('id' => '176', 'code' => 'PL'),
            array('id' => '177', 'code' => 'PT'),
            array('id' => '178', 'code' => 'PR'),
            array('id' => '179', 'code' => 'QA'),
            array('id' => '180', 'code' => 'RE'),
            array('id' => '181', 'code' => 'RO'),
            array('id' => '182', 'code' => 'RU'),
            array('id' => '183', 'code' => 'RW'),
            array('id' => '184', 'code' => 'KN'),
            array('id' => '185', 'code' => 'LC'),
            array('id' => '186', 'code' => 'VC'),
            array('id' => '187', 'code' => 'WS'),
            array('id' => '188', 'code' => 'SM'),
            array('id' => '189', 'code' => 'ST'),
            array('id' => '190', 'code' => 'SA'),
            array('id' => '191', 'code' => 'SN'),
            array('id' => '192', 'code' => 'RS'),
            array('id' => '193', 'code' => 'SC'),
            array('id' => '194', 'code' => 'SL'),
            array('id' => '195', 'code' => 'SG'),
            array('id' => '196', 'code' => 'SK'),
            array('id' => '197', 'code' => 'SI'),
            array('id' => '198', 'code' => 'SB'),
            array('id' => '199', 'code' => 'SO'),
            array('id' => '200', 'code' => 'ZA'),
            array('id' => '201', 'code' => 'GS'),
            array('id' => '202', 'code' => 'ES'),
            array('id' => '203', 'code' => 'LK'),
            array('id' => '204', 'code' => 'SH'),
            array('id' => '205', 'code' => 'PM'),
            array('id' => '206', 'code' => 'SD'),
            array('id' => '207', 'code' => 'SR'),
            array('id' => '208', 'code' => 'SJ'),
            array('id' => '209', 'code' => 'SZ'),
            array('id' => '210', 'code' => 'SE'),
            array('id' => '211', 'code' => 'CH'),
            array('id' => '212', 'code' => 'SY'),
            array('id' => '213', 'code' => 'TW'),
            array('id' => '214', 'code' => 'TJ'),
            array('id' => '215', 'code' => 'TZ'),
            array('id' => '216', 'code' => 'TH'),
            array('id' => '217', 'code' => 'TG'),
            array('id' => '218', 'code' => 'TK'),
            array('id' => '219', 'code' => 'TO'),
            array('id' => '220', 'code' => 'TT'),
            array('id' => '221', 'code' => 'TN'),
            array('id' => '222', 'code' => 'TR'),
            array('id' => '223', 'code' => 'TM'),
            array('id' => '224', 'code' => 'TC'),
            array('id' => '225', 'code' => 'TV'),
            array('id' => '226', 'code' => 'UG'),
            array('id' => '227', 'code' => 'UA'),
            array('id' => '228', 'code' => 'AE'),
            array('id' => '229', 'code' => 'GB'),
            array('id' => '230', 'code' => 'US'),
            array('id' => '231', 'code' => 'UM'),
            array('id' => '232', 'code' => 'UY'),
            array('id' => '233', 'code' => 'UZ'),
            array('id' => '234', 'code' => 'VU'),
            array('id' => '235', 'code' => 'VA'),
            array('id' => '236', 'code' => 'VE'),
            array('id' => '237', 'code' => 'VN'),
            array('id' => '238', 'code' => 'VG'),
            array('id' => '239', 'code' => 'VI'),
            array('id' => '240', 'code' => 'WF'),
            array('id' => '241', 'code' => 'EH'),
            array('id' => '242', 'code' => 'YE'),
            array('id' => '243', 'code' => 'ZR'),
            array('id' => '244', 'code' => 'ZM'),
            array('id' => '245', 'code' => 'ZW'),
        ];
        Country::insert($countries);

        \DB::table('country_translations')->truncate();
        $countriesTranslations = [
            array('country_id' => '1',   'locale' => 'en', 'name' => 'Afghanistan',),
            array('country_id' => '1',   'locale' => 'ar', 'name' => 'Afghanistan',),
            array('country_id' => '2',   'locale' => 'en', 'name' => 'Albania',),
            array('country_id' => '2',   'locale' => 'ar', 'name' => 'Albania',),
            array('country_id' => '3',   'locale' => 'ar', 'name' => 'Algeria',),
            array('country_id' => '3',   'locale' => 'en', 'name' => 'Algeria',),
            array('country_id' => '4',   'locale' => 'en', 'name' => 'American Samoa',),
            array('country_id' => '4',   'locale' => 'ar', 'name' => 'American Samoa',),
            array('country_id' => '5',   'locale' => 'en', 'name' => 'Andorra',),
            array('country_id' => '5',   'locale' => 'ar', 'name' => 'Andorra',),
            array('country_id' => '6',   'locale' => 'en', 'name' => 'Angola',),
            array('country_id' => '6',   'locale' => 'ar', 'name' => 'Angola',),
            array('country_id' => '7',   'locale' => 'en', 'name' => 'Anguilla',),
            array('country_id' => '7',   'locale' => 'ar', 'name' => 'Anguilla',),
            array('country_id' => '8',   'locale' => 'en', 'name' => 'Antarctica',),
            array('country_id' => '8',   'locale' => 'ar', 'name' => 'Antarctica',),
            array('country_id' => '9',   'locale' => 'en', 'name' => 'Antigua and Barbuda',),
            array('country_id' => '9',   'locale' => 'ar', 'name' => 'Antigua and Barbuda',),
            array('country_id' => '10',  'locale' => 'en', 'name' => 'Argentina',),
            array('country_id' => '10',  'locale' => 'ar', 'name' => 'Argentina',),
            array('country_id' => '11',  'locale' => 'en', 'name' => 'Armenia',),
            array('country_id' => '11',  'locale' => 'ar', 'name' => 'Armenia',),
            array('country_id' => '12',  'locale' => 'en', 'name' => 'Aruba',),
            array('country_id' => '12',  'locale' => 'ar', 'name' => 'Aruba',),
            array('country_id' => '13',  'locale' => 'en', 'name' => 'Australia',),
            array('country_id' => '13',  'locale' => 'ar', 'name' => 'Australia',),
            array('country_id' => '14',  'locale' => 'en', 'name' => 'Austria',),
            array('country_id' => '14',  'locale' => 'ar', 'name' => 'Austria',),
            array('country_id' => '15',  'locale' => 'en', 'name' => 'Azerbaijan',),
            array('country_id' => '15',  'locale' => 'ar', 'name' => 'Azerbaijan',),
            array('country_id' => '16',  'locale' => 'en', 'name' => 'Bahamas',),
            array('country_id' => '16',  'locale' => 'ar', 'name' => 'Bahamas',),
            array('country_id' => '17',  'locale' => 'en', 'name' => 'Bahrain',),
            array('country_id' => '17',  'locale' => 'ar', 'name' => 'Bahrain',),
            array('country_id' => '18',  'locale' => 'en', 'name' => 'Bangladesh',),
            array('country_id' => '18',  'locale' => 'ar', 'name' => 'Bangladesh',),
            array('country_id' => '19',  'locale' => 'en', 'name' => 'Barbados',),
            array('country_id' => '19',  'locale' => 'ar', 'name' => 'Barbados',),
            array('country_id' => '20',  'locale' => 'en', 'name' => 'Belarus',),
            array('country_id' => '20',  'locale' => 'ar', 'name' => 'Belarus',),
            array('country_id' => '21',  'locale' => 'en', 'name' => 'Belgium',),
            array('country_id' => '21',  'locale' => 'ar', 'name' => 'Belgium',),
            array('country_id' => '22',  'locale' => 'en', 'name' => 'Belize',),
            array('country_id' => '22',  'locale' => 'ar', 'name' => 'Belize',),
            array('country_id' => '23',  'locale' => 'en', 'name' => 'Benin',),
            array('country_id' => '23',  'locale' => 'ar', 'name' => 'Benin',),
            array('country_id' => '24',  'locale' => 'en', 'name' => 'Bermuda',),
            array('country_id' => '24',  'locale' => 'ar', 'name' => 'Bermuda',),
            array('country_id' => '25',  'locale' => 'en', 'name' => 'Bhutan',),
            array('country_id' => '25',  'locale' => 'ar', 'name' => 'Bhutan',),
            array('country_id' => '26',  'locale' => 'en', 'name' => 'Bolivia',),
            array('country_id' => '26',  'locale' => 'ar', 'name' => 'Bolivia',),
            array('country_id' => '27',  'locale' => 'en', 'name' => 'Bosnia and Herzegovina',),
            array('country_id' => '27',  'locale' => 'ar', 'name' => 'Bosnia and Herzegovina',),
            array('country_id' => '28',  'locale' => 'en', 'name' => 'Botswana',),
            array('country_id' => '28',  'locale' => 'ar', 'name' => 'Botswana',),
            array('country_id' => '29',  'locale' => 'en', 'name' => 'Bouvet Island',),
            array('country_id' => '29',  'locale' => 'ar', 'name' => 'Bouvet Island',),
            array('country_id' => '31',  'locale' => 'en', 'name' => 'Brazil',),
            array('country_id' => '31',  'locale' => 'ar', 'name' => 'Brazil',),
            array('country_id' => '32',  'locale' => 'en', 'name' => 'British Indian Ocean Territory',),
            array('country_id' => '32',  'locale' => 'ar', 'name' => 'British Indian Ocean Territory',),
            array('country_id' => '33',  'locale' => 'en', 'name' => 'Brunei Darussalam',),
            array('country_id' => '33',  'locale' => 'ar', 'name' => 'Brunei Darussalam',),
            array('country_id' => '34',  'locale' => 'en', 'name' => 'Bulgaria',),
            array('country_id' => '34',  'locale' => 'ar', 'name' => 'Bulgaria',),
            array('country_id' => '35',  'locale' => 'en', 'name' => 'Burkina Faso',),
            array('country_id' => '35',  'locale' => 'ar', 'name' => 'Burkina Faso',),
            array('country_id' => '36',  'locale' => 'en', 'name' => 'Burundi',),
            array('country_id' => '36',  'locale' => 'ar', 'name' => 'Burundi',),
            array('country_id' => '37',  'locale' => 'en', 'name' => 'Cambodia',),
            array('country_id' => '37',  'locale' => 'ar', 'name' => 'Cambodia',),
            array('country_id' => '38',  'locale' => 'en', 'name' => 'Cameroon',),
            array('country_id' => '38',  'locale' => 'ar', 'name' => 'Cameroon',),
            array('country_id' => '39',  'locale' => 'en', 'name' => 'Canada',),
            array('country_id' => '39',  'locale' => 'ar', 'name' => 'Canada',),
            array('country_id' => '40',  'locale' => 'en', 'name' => 'Cape Verde',),
            array('country_id' => '40',  'locale' => 'ar', 'name' => 'Cape Verde',),
            array('country_id' => '41',  'locale' => 'en', 'name' => 'Cayman Islands',),
            array('country_id' => '41',  'locale' => 'ar', 'name' => 'Cayman Islands',),
            array('country_id' => '42',  'locale' => 'en', 'name' => 'Central African Republic',),
            array('country_id' => '42',  'locale' => 'ar', 'name' => 'Central African Republic',),
            array('country_id' => '43',  'locale' => 'en', 'name' => 'Chad',),
            array('country_id' => '43',  'locale' => 'ar', 'name' => 'Chad',),
            array('country_id' => '44',  'locale' => 'en', 'name' => 'Chile',),
            array('country_id' => '44',  'locale' => 'ar', 'name' => 'Chile',),
            array('country_id' => '45',  'locale' => 'en', 'name' => 'China',),
            array('country_id' => '45',  'locale' => 'ar', 'name' => 'China',),
            array('country_id' => '46',  'locale' => 'en', 'name' => 'Christmas Island',),
            array('country_id' => '46',  'locale' => 'ar', 'name' => 'Christmas Island',),
            array('country_id' => '47',  'locale' => 'en', 'name' => 'Cocos (Keeling) Islands',),
            array('country_id' => '47',  'locale' => 'ar', 'name' => 'Cocos (Keeling) Islands',),
            array('country_id' => '48',  'locale' => 'en', 'name' => 'Colombia',),
            array('country_id' => '48',  'locale' => 'ar', 'name' => 'Colombia',),
            array('country_id' => '49',  'locale' => 'en', 'name' => 'Comoros',),
            array('country_id' => '49',  'locale' => 'ar', 'name' => 'Comoros',),
            array('country_id' => '50',  'locale' => 'en', 'name' => 'Congo',),
            array('country_id' => '50',  'locale' => 'ar', 'name' => 'Congo',),
            array('country_id' => '51',  'locale' => 'en', 'name' => 'Cook Islands',),
            array('country_id' => '51',  'locale' => 'ar', 'name' => 'Cook Islands',),
            array('country_id' => '52',  'locale' => 'en', 'name' => 'Costa Rica',),
            array('country_id' => '52',  'locale' => 'ar', 'name' => 'Costa Rica',),
            array('country_id' => '53',  'locale' => 'en', 'name' => 'Croatia (Hrvatska)',),
            array('country_id' => '53',  'locale' => 'ar', 'name' => 'Croatia (Hrvatska)',),
            array('country_id' => '54',  'locale' => 'en', 'name' => 'Cuba',),
            array('country_id' => '54',  'locale' => 'ar', 'name' => 'Cuba',),
            array('country_id' => '55',  'locale' => 'en', 'name' => 'Cyprus',),
            array('country_id' => '55',  'locale' => 'ar', 'name' => 'Cyprus',),
            array('country_id' => '56',  'locale' => 'en', 'name' => 'Czech Republic',),
            array('country_id' => '56',  'locale' => 'ar', 'name' => 'Czech Republic',),
            array('country_id' => '57',  'locale' => 'en', 'name' => 'Denmark',),
            array('country_id' => '57',  'locale' => 'ar', 'name' => 'Denmark',),
            array('country_id' => '58',  'locale' => 'en', 'name' => 'Djibouti',),
            array('country_id' => '58',  'locale' => 'ar', 'name' => 'Djibouti',),
            array('country_id' => '59',  'locale' => 'en', 'name' => 'Dominica',),
            array('country_id' => '59',  'locale' => 'ar', 'name' => 'Dominica',),
            array('country_id' => '60',  'locale' => 'en', 'name' => 'Dominican Republic',),
            array('country_id' => '60',  'locale' => 'ar', 'name' => 'Dominican Republic',),
            array('country_id' => '61',  'locale' => 'en', 'name' => 'East Timor',),
            array('country_id' => '61',  'locale' => 'ar', 'name' => 'East Timor',),
            array('country_id' => '62',  'locale' => 'en', 'name' => 'Ecuador',),
            array('country_id' => '62',  'locale' => 'ar', 'name' => 'Ecuador',),
            array('country_id' => '63',  'locale' => 'en', 'name' => 'Egypt',),
            array('country_id' => '63',  'locale' => 'ar', 'name' => 'Egypt',),
            array('country_id' => '64',  'locale' => 'en', 'name' => 'El Salvador',),
            array('country_id' => '64',  'locale' => 'ar', 'name' => 'El Salvador',),
            array('country_id' => '65',  'locale' => 'en', 'name' => 'Equatorial Guinea',),
            array('country_id' => '65',  'locale' => 'ar', 'name' => 'Equatorial Guinea',),
            array('country_id' => '66',  'locale' => 'en', 'name' => 'Eritrea',),
            array('country_id' => '66',  'locale' => 'ar', 'name' => 'Eritrea',),
            array('country_id' => '67',  'locale' => 'en', 'name' => 'Estonia',),
            array('country_id' => '67',  'locale' => 'ar', 'name' => 'Estonia',),
            array('country_id' => '68',  'locale' => 'en', 'name' => 'Ethiopia',),
            array('country_id' => '68',  'locale' => 'ar', 'name' => 'Ethiopia',),
            array('country_id' => '69',  'locale' => 'en', 'name' => 'Falkland Islands (Malvinas)',),
            array('country_id' => '69',  'locale' => 'ar', 'name' => 'Falkland Islands (Malvinas)',),
            array('country_id' => '70',  'locale' => 'en', 'name' => 'Faroe Islands',),
            array('country_id' => '70',  'locale' => 'ar', 'name' => 'Faroe Islands',),
            array('country_id' => '71',  'locale' => 'en', 'name' => 'Fiji',),
            array('country_id' => '71',  'locale' => 'ar', 'name' => 'Fiji',),
            array('country_id' => '72',  'locale' => 'en', 'name' => 'Finland',),
            array('country_id' => '72',  'locale' => 'ar', 'name' => 'Finland',),
            array('country_id' => '73',  'locale' => 'en', 'name' => 'France',),
            array('country_id' => '73',  'locale' => 'ar', 'name' => 'France',),
            array('country_id' => '74',  'locale' => 'en', 'name' => 'French Guiana',),
            array('country_id' => '74',  'locale' => 'ar', 'name' => 'French Guiana',),
            array('country_id' => '75',  'locale' => 'en', 'name' => 'French Polynesia',),
            array('country_id' => '75',  'locale' => 'ar', 'name' => 'French Polynesia',),
            array('country_id' => '76',  'locale' => 'en', 'name' => 'French Southern Territories',),
            array('country_id' => '76',  'locale' => 'ar', 'name' => 'French Southern Territories',),
            array('country_id' => '77',  'locale' => 'en', 'name' => 'Gabon',),
            array('country_id' => '77',  'locale' => 'ar', 'name' => 'Gabon',),
            array('country_id' => '78',  'locale' => 'en', 'name' => 'Gambia',),
            array('country_id' => '78',  'locale' => 'ar', 'name' => 'Gambia',),
            array('country_id' => '79',  'locale' => 'en', 'name' => 'Georgia',),
            array('country_id' => '79',  'locale' => 'ar', 'name' => 'Georgia',),
            array('country_id' => '80',  'locale' => 'en', 'name' => 'Germany',),
            array('country_id' => '80',  'locale' => 'ar', 'name' => 'Germany',),
            array('country_id' => '81',  'locale' => 'en', 'name' => 'Ghana',),
            array('country_id' => '81',  'locale' => 'ar', 'name' => 'Ghana',),
            array('country_id' => '82',  'locale' => 'en', 'name' => 'Gibraltar',),
            array('country_id' => '82',  'locale' => 'ar', 'name' => 'Gibraltar',),
            array('country_id' => '83',  'locale' => 'en', 'name' => 'Guernsey',),
            array('country_id' => '83',  'locale' => 'ar', 'name' => 'Guernsey',),
            array('country_id' => '84',  'locale' => 'en', 'name' => 'Greece',),
            array('country_id' => '84',  'locale' => 'ar', 'name' => 'Greece',),
            array('country_id' => '85',  'locale' => 'en', 'name' => 'Greenland',),
            array('country_id' => '85',  'locale' => 'ar', 'name' => 'Greenland',),
            array('country_id' => '86',  'locale' => 'en', 'name' => 'Grenada',),
            array('country_id' => '86',  'locale' => 'ar', 'name' => 'Grenada',),
            array('country_id' => '87',  'locale' => 'en', 'name' => 'Guadeloupe',),
            array('country_id' => '87',  'locale' => 'ar', 'name' => 'Guadeloupe',),
            array('country_id' => '88',  'locale' => 'en', 'name' => 'Guam',),
            array('country_id' => '88',  'locale' => 'ar', 'name' => 'Guam',),
            array('country_id' => '89',  'locale' => 'en', 'name' => 'Guatemala',),
            array('country_id' => '89',  'locale' => 'ar', 'name' => 'Guatemala',),
            array('country_id' => '90',  'locale' => 'en', 'name' => 'Guinea',),
            array('country_id' => '90',  'locale' => 'ar', 'name' => 'Guinea',),
            array('country_id' => '91',  'locale' => 'en', 'name' => 'Guinea-Bissau',),
            array('country_id' => '91',  'locale' => 'ar', 'name' => 'Guinea-Bissau',),
            array('country_id' => '92',  'locale' => 'en', 'name' => 'Guyana',),
            array('country_id' => '92',  'locale' => 'ar', 'name' => 'Guyana',),
            array('country_id' => '93',  'locale' => 'en', 'name' => 'Haiti',),
            array('country_id' => '93',  'locale' => 'ar', 'name' => 'Haiti',),
            array('country_id' => '94',  'locale' => 'en', 'name' => 'Heard and Mc Donald Islands'),
            array('country_id' => '94',  'locale' => 'ar', 'name' => 'Heard and Mc Donald Islands'),
            array('country_id' => '95',  'locale' => 'en', 'name' => 'Honduras',),
            array('country_id' => '95',  'locale' => 'ar', 'name' => 'Honduras',),
            array('country_id' => '96',  'locale' => 'en', 'name' => 'Hong Kong'),
            array('country_id' => '96',  'locale' => 'ar', 'name' => 'Hong Kong'),
            array('country_id' => '97',  'locale' => 'en', 'name' => 'Hungary',),
            array('country_id' => '97',  'locale' => 'ar', 'name' => 'Hungary',),
            array('country_id' => '98',  'locale' => 'en', 'name' => 'Iceland',),
            array('country_id' => '98',  'locale' => 'ar', 'name' => 'Iceland',),
            array('country_id' => '99',  'locale' => 'en', 'name' => 'India',),
            array('country_id' => '99',  'locale' => 'ar', 'name' => 'India',),
            array('country_id' => '100', 'locale' => 'en', 'name' => 'Isle of Man',),
            array('country_id' => '100', 'locale' => 'ar', 'name' => 'Isle of Man',),
            array('country_id' => '101', 'locale' => 'en', 'name' => 'Indonesia',),
            array('country_id' => '101', 'locale' => 'ar', 'name' => 'Indonesia',),
            array('country_id' => '102', 'locale' => 'en', 'name' => 'Iran',),
            array('country_id' => '102', 'locale' => 'ar', 'name' => 'Iran',),
            array('country_id' => '103', 'locale' => 'en', 'name' => 'Iraq',),
            array('country_id' => '103', 'locale' => 'ar', 'name' => 'Iraq',),
            array('country_id' => '104', 'locale' => 'en', 'name' => 'Ireland',),
            array('country_id' => '104', 'locale' => 'ar', 'name' => 'Ireland',),
            array('country_id' => '105', 'locale' => 'en', 'name' => 'Israel',),
            array('country_id' => '105', 'locale' => 'ar', 'name' => 'Israel',),
            array('country_id' => '106', 'locale' => 'en', 'name' => 'Italy',),
            array('country_id' => '106', 'locale' => 'ar', 'name' => 'Italy',),
            array('country_id' => '107', 'locale' => 'en', 'name' => 'Ivory Coast',),
            array('country_id' => '107', 'locale' => 'ar', 'name' => 'Ivory Coast',),
            array('country_id' => '108', 'locale' => 'en', 'name' => 'Jersey',),
            array('country_id' => '108', 'locale' => 'ar', 'name' => 'Jersey',),
            array('country_id' => '109', 'locale' => 'en', 'name' => 'Jamaica',),
            array('country_id' => '109', 'locale' => 'ar', 'name' => 'Jamaica',),
            array('country_id' => '110', 'locale' => 'en', 'name' => 'Japan',),
            array('country_id' => '110', 'locale' => 'ar', 'name' => 'Japan',),
            array('country_id' => '111', 'locale' => 'en', 'name' => 'Jordan',),
            array('country_id' => '111', 'locale' => 'ar', 'name' => 'Jordan',),
            array('country_id' => '112', 'locale' => 'en', 'name' => 'Kazakhstan',),
            array('country_id' => '112', 'locale' => 'ar', 'name' => 'Kazakhstan',),
            array('country_id' => '113', 'locale' => 'en', 'name' => 'Kenya',),
            array('country_id' => '113', 'locale' => 'ar', 'name' => 'Kenya',),
            array('country_id' => '114', 'locale' => 'en', 'name' => 'Kiribati'),
            array('country_id' => '114', 'locale' => 'ar', 'name' => 'Kiribati'),
            array('country_id' => '115', 'locale' => 'en', 'name' => 'Democratic Peoples Republic of Korea',),
            array('country_id' => '115', 'locale' => 'ar', 'name' => 'Democratic Peoples Republic of Korea',),
            array('country_id' => '116', 'locale' => 'en', 'name' => 'Republic of Korea ',),
            array('country_id' => '116', 'locale' => 'ar', 'name' => 'Republic of Korea ',),
            array('country_id' => '117', 'locale' => 'en', 'name' => 'Kosovo',),
            array('country_id' => '117', 'locale' => 'ar', 'name' => 'Kosovo',),
            array('country_id' => '118', 'locale' => 'en', 'name' => 'Kuwait',),
            array('country_id' => '118', 'locale' => 'ar', 'name' => 'Kuwait',),
            array('country_id' => '119', 'locale' => 'en', 'name' => 'Kyrgyzstan',),
            array('country_id' => '119', 'locale' => 'ar', 'name' => 'Kyrgyzstan',),
            array('country_id' => '120', 'locale' => 'en', 'name' => 'Lao Peoples Democratic Republic',),
            array('country_id' => '120', 'locale' => 'ar', 'name' => 'Lao Peoples Democratic Republic',),
            array('country_id' => '121', 'locale' => 'en', 'name' => 'Latvia',),
            array('country_id' => '121', 'locale' => 'ar', 'name' => 'Latvia',),
            array('country_id' => '122', 'locale' => 'en', 'name' => 'Lebanon',),
            array('country_id' => '122', 'locale' => 'ar', 'name' => 'Lebanon',),
            array('country_id' => '123', 'locale' => 'en', 'name' => 'Lesotho',),
            array('country_id' => '123', 'locale' => 'ar', 'name' => 'Lesotho',),
            array('country_id' => '124', 'locale' => 'en', 'name' => 'Liberia',),
            array('country_id' => '124', 'locale' => 'ar', 'name' => 'Liberia',),
            array('country_id' => '125', 'locale' => 'en', 'name' => 'Libyan Arab Jamahiriya',),
            array('country_id' => '125', 'locale' => 'ar', 'name' => 'Libyan Arab Jamahiriya',),
            array('country_id' => '126', 'locale' => 'en', 'name' => 'Liechtenstein',),
            array('country_id' => '126', 'locale' => 'ar', 'name' => 'Liechtenstein',),
            array('country_id' => '127', 'locale' => 'en', 'name' => 'Lithuania',),
            array('country_id' => '127', 'locale' => 'ar', 'name' => 'Lithuania',),
            array('country_id' => '128', 'locale' => 'en', 'name' => 'Luxembourg',),
            array('country_id' => '128', 'locale' => 'ar', 'name' => 'Luxembourg',),
            array('country_id' => '129', 'locale' => 'en', 'name' => 'Macau',),
            array('country_id' => '129', 'locale' => 'ar', 'name' => 'Macau',),
            array('country_id' => '130', 'locale' => 'en', 'name' => 'Macedonia',),
            array('country_id' => '130', 'locale' => 'ar', 'name' => 'Macedonia',),
            array('country_id' => '131', 'locale' => 'en', 'name' => 'Madagascar',),
            array('country_id' => '131', 'locale' => 'ar', 'name' => 'Madagascar',),
            array('country_id' => '132', 'locale' => 'en', 'name' => 'Malawi',),
            array('country_id' => '132', 'locale' => 'ar', 'name' => 'Malawi',),
            array('country_id' => '133', 'locale' => 'en', 'name' => 'Malaysia',),
            array('country_id' => '133', 'locale' => 'ar', 'name' => 'Malaysia',),
            array('country_id' => '134', 'locale' => 'en', 'name' => 'Maldives',),
            array('country_id' => '134', 'locale' => 'ar', 'name' => 'Maldives',),
            array('country_id' => '135', 'locale' => 'en', 'name' => 'Mali',),
            array('country_id' => '135', 'locale' => 'ar', 'name' => 'Mali',),
            array('country_id' => '136', 'locale' => 'en', 'name' => 'Malta',),
            array('country_id' => '136', 'locale' => 'ar', 'name' => 'Malta',),
            array('country_id' => '137', 'locale' => 'en', 'name' => 'Marshall Islands',),
            array('country_id' => '137', 'locale' => 'ar', 'name' => 'Marshall Islands',),
            array('country_id' => '138', 'locale' => 'en', 'name' => 'Martinique',),
            array('country_id' => '138', 'locale' => 'ar', 'name' => 'Martinique',),
            array('country_id' => '139', 'locale' => 'en', 'name' => 'Mauritania',),
            array('country_id' => '139', 'locale' => 'ar', 'name' => 'Mauritania',),
            array('country_id' => '140', 'locale' => 'en', 'name' => 'Mauritius',),
            array('country_id' => '140', 'locale' => 'ar', 'name' => 'Mauritius',),
            array('country_id' => '141', 'locale' => 'en', 'name' => 'Mayotte',),
            array('country_id' => '141', 'locale' => 'ar', 'name' => 'Mayotte',),
            array('country_id' => '142', 'locale' => 'en', 'name' => 'Mexico',),
            array('country_id' => '142', 'locale' => 'ar', 'name' => 'Mexico',),
            array('country_id' => '143', 'locale' => 'en', 'name' => 'Federated States of Micronesia',),
            array('country_id' => '143', 'locale' => 'ar', 'name' => 'Federated States of Micronesia',),
            array('country_id' => '144', 'locale' => 'en', 'name' => 'Republic of Moldova',),
            array('country_id' => '144', 'locale' => 'ar', 'name' => 'Republic of Moldova',),
            array('country_id' => '145', 'locale' => 'en', 'name' => 'Monaco',),
            array('country_id' => '145', 'locale' => 'ar', 'name' => 'Monaco',),
            array('country_id' => '146', 'locale' => 'en', 'name' => 'Mongolia',),
            array('country_id' => '146', 'locale' => 'ar', 'name' => 'Mongolia',),
            array('country_id' => '147', 'locale' => 'en', 'name' => 'Montenegro',),
            array('country_id' => '147', 'locale' => 'ar', 'name' => 'Montenegro',),
            array('country_id' => '148', 'locale' => 'en', 'name' => 'Montserrat',),
            array('country_id' => '148', 'locale' => 'ar', 'name' => 'Montserrat',),
            array('country_id' => '149', 'locale' => 'en', 'name' => 'Morocco',),
            array('country_id' => '149', 'locale' => 'ar', 'name' => 'Morocco',),
            array('country_id' => '150', 'locale' => 'en', 'name' => 'Mozambique',),
            array('country_id' => '150', 'locale' => 'ar', 'name' => 'Mozambique',),
            array('country_id' => '151', 'locale' => 'en', 'name' => 'Myanmar',),
            array('country_id' => '151', 'locale' => 'ar', 'name' => 'Myanmar',),
            array('country_id' => '152', 'locale' => 'en', 'name' => 'Namibia',),
            array('country_id' => '152', 'locale' => 'ar', 'name' => 'Namibia',),
            array('country_id' => '153', 'locale' => 'en', 'name' => 'Nauru',),
            array('country_id' => '153', 'locale' => 'ar', 'name' => 'Nauru',),
            array('country_id' => '154', 'locale' => 'en', 'name' => 'Nepal',),
            array('country_id' => '154', 'locale' => 'ar', 'name' => 'Nepal',),
            array('country_id' => '155', 'locale' => 'en', 'name' => 'Netherlands',),
            array('country_id' => '155', 'locale' => 'ar', 'name' => 'Netherlands',),
            array('country_id' => '156', 'locale' => 'en', 'name' => 'Netherlands Antilles',),
            array('country_id' => '156', 'locale' => 'ar', 'name' => 'Netherlands Antilles',),
            array('country_id' => '157', 'locale' => 'en', 'name' => 'New Caledonia',),
            array('country_id' => '157', 'locale' => 'ar', 'name' => 'New Caledonia',),
            array('country_id' => '158', 'locale' => 'en', 'name' => 'New Zealand',),
            array('country_id' => '158', 'locale' => 'ar', 'name' => 'New Zealand',),
            array('country_id' => '159', 'locale' => 'en', 'name' => 'Nicaragua',),
            array('country_id' => '159', 'locale' => 'ar', 'name' => 'Nicaragua',),
            array('country_id' => '160', 'locale' => 'en', 'name' => 'Niger',),
            array('country_id' => '160', 'locale' => 'ar', 'name' => 'Niger',),
            array('country_id' => '161', 'locale' => 'en', 'name' => 'Nigeria',),
            array('country_id' => '161', 'locale' => 'ar', 'name' => 'Nigeria',),
            array('country_id' => '162', 'locale' => 'en', 'name' => 'Niue',),
            array('country_id' => '162', 'locale' => 'ar', 'name' => 'Niue',),
            array('country_id' => '163', 'locale' => 'en', 'name' => 'Norfolk Island',),
            array('country_id' => '163', 'locale' => 'ar', 'name' => 'Norfolk Island',),
            array('country_id' => '164', 'locale' => 'en', 'name' => 'Northern Mariana Islands',),
            array('country_id' => '164', 'locale' => 'ar', 'name' => 'Northern Mariana Islands',),
            array('country_id' => '165', 'locale' => 'en', 'name' => 'Norway',),
            array('country_id' => '165', 'locale' => 'ar', 'name' => 'Norway',),
            array('country_id' => '166', 'locale' => 'en', 'name' => 'Oman',),
            array('country_id' => '166', 'locale' => 'ar', 'name' => 'Oman',),
            array('country_id' => '167', 'locale' => 'en', 'name' => 'Pakistan',),
            array('country_id' => '167', 'locale' => 'ar', 'name' => 'Pakistan',),
            array('country_id' => '168', 'locale' => 'en', 'name' => 'Palau',),
            array('country_id' => '168', 'locale' => 'ar', 'name' => 'Palau',),
            array('country_id' => '169', 'locale' => 'en', 'name' => 'Palestine',),
            array('country_id' => '169', 'locale' => 'ar', 'name' => 'Palestine',),
            array('country_id' => '170', 'locale' => 'en', 'name' => 'Panama',),
            array('country_id' => '170', 'locale' => 'ar', 'name' => 'Panama',),
            array('country_id' => '171', 'locale' => 'en', 'name' => 'Papua New Guinea',),
            array('country_id' => '171', 'locale' => 'ar', 'name' => 'Papua New Guinea',),
            array('country_id' => '172', 'locale' => 'en', 'name' => 'Paraguay',),
            array('country_id' => '172', 'locale' => 'ar', 'name' => 'Paraguay',),
            array('country_id' => '173', 'locale' => 'en', 'name' => 'Peru',),
            array('country_id' => '173', 'locale' => 'ar', 'name' => 'Peru',),
            array('country_id' => '174', 'locale' => 'en', 'name' => 'Philippines',),
            array('country_id' => '174', 'locale' => 'ar', 'name' => 'Philippines',),
            array('country_id' => '175', 'locale' => 'en', 'name' => 'Pitcairn',),
            array('country_id' => '175', 'locale' => 'ar', 'name' => 'Pitcairn',),
            array('country_id' => '176', 'locale' => 'en', 'name' => 'Poland',),
            array('country_id' => '176', 'locale' => 'ar', 'name' => 'Poland',),
            array('country_id' => '177', 'locale' => 'en', 'name' => 'Portugal',),
            array('country_id' => '177', 'locale' => 'ar', 'name' => 'Portugal',),
            array('country_id' => '178', 'locale' => 'en', 'name' => 'Puerto Rico',),
            array('country_id' => '178', 'locale' => 'ar', 'name' => 'Puerto Rico',),
            array('country_id' => '179', 'locale' => 'en', 'name' => 'Qatar',),
            array('country_id' => '179', 'locale' => 'ar', 'name' => 'Qatar',),
            array('country_id' => '180', 'locale' => 'en', 'name' => 'Reunion',),
            array('country_id' => '180', 'locale' => 'ar', 'name' => 'Reunion',),
            array('country_id' => '181', 'locale' => 'en', 'name' => 'Romania',),
            array('country_id' => '181', 'locale' => 'ar', 'name' => 'Romania',),
            array('country_id' => '182', 'locale' => 'en', 'name' => 'Russian Federation',),
            array('country_id' => '182', 'locale' => 'ar', 'name' => 'Russian Federation',),
            array('country_id' => '183', 'locale' => 'en', 'name' => 'Rwanda',),
            array('country_id' => '183', 'locale' => 'ar', 'name' => 'Rwanda',),
            array('country_id' => '184', 'locale' => 'en', 'name' => 'Saint Kitts and Nevis',),
            array('country_id' => '184', 'locale' => 'ar', 'name' => 'Saint Kitts and Nevis',),
            array('country_id' => '185', 'locale' => 'en', 'name' => 'Saint Lucia',),
            array('country_id' => '185', 'locale' => 'ar', 'name' => 'Saint Lucia',),
            array('country_id' => '186', 'locale' => 'en', 'name' => 'Saint Vincent and the Grenadines',),
            array('country_id' => '186', 'locale' => 'ar', 'name' => 'Saint Vincent and the Grenadines',),
            array('country_id' => '187', 'locale' => 'en', 'name' => 'Samoa',),
            array('country_id' => '187', 'locale' => 'ar', 'name' => 'Samoa',),
            array('country_id' => '188', 'locale' => 'en', 'name' => 'San Marino',),
            array('country_id' => '188', 'locale' => 'ar', 'name' => 'San Marino',),
            array('country_id' => '189', 'locale' => 'en', 'name' => 'Sao Tome and Principe',),
            array('country_id' => '189', 'locale' => 'ar', 'name' => 'Sao Tome and Principe',),
            array('country_id' => '190', 'locale' => 'en', 'name' => 'Saudi Arabia',),
            array('country_id' => '190', 'locale' => 'ar', 'name' => 'Saudi Arabia',),
            array('country_id' => '191', 'locale' => 'en', 'name' => 'Senegal',),
            array('country_id' => '191', 'locale' => 'ar', 'name' => 'Senegal',),
            array('country_id' => '192', 'locale' => 'en', 'name' => 'Serbia',),
            array('country_id' => '192', 'locale' => 'ar', 'name' => 'Serbia',),
            array('country_id' => '193', 'locale' => 'en', 'name' => 'Seychelles',),
            array('country_id' => '193', 'locale' => 'ar', 'name' => 'Seychelles',),
            array('country_id' => '194', 'locale' => 'en', 'name' => 'Sierra Leone',),
            array('country_id' => '194', 'locale' => 'ar', 'name' => 'Sierra Leone',),
            array('country_id' => '195', 'locale' => 'en', 'name' => 'Singapore',),
            array('country_id' => '195', 'locale' => 'ar', 'name' => 'Singapore',),
            array('country_id' => '196', 'locale' => 'en', 'name' => 'Slovakia',),
            array('country_id' => '196', 'locale' => 'ar', 'name' => 'Slovakia',),
            array('country_id' => '197', 'locale' => 'en', 'name' => 'Slovenia',),
            array('country_id' => '197', 'locale' => 'ar', 'name' => 'Slovenia',),
            array('country_id' => '198', 'locale' => 'en', 'name' => 'Solomon Islands',),
            array('country_id' => '198', 'locale' => 'ar', 'name' => 'Solomon Islands',),
            array('country_id' => '199', 'locale' => 'en', 'name' => 'Somalia',),
            array('country_id' => '199', 'locale' => 'ar', 'name' => 'Somalia',),
            array('country_id' => '200', 'locale' => 'en', 'name' => 'South Africa',),
            array('country_id' => '200', 'locale' => 'ar', 'name' => 'South Africa',),
            array('country_id' => '201', 'locale' => 'en', 'name' => 'South Georgia South Sandwich Islands',),
            array('country_id' => '201', 'locale' => 'ar', 'name' => 'South Georgia South Sandwich Islands',),
            array('country_id' => '202', 'locale' => 'en', 'name' => 'Spain',),
            array('country_id' => '202', 'locale' => 'ar', 'name' => 'Spain',),
            array('country_id' => '203', 'locale' => 'en', 'name' => 'Sri Lanka',),
            array('country_id' => '203', 'locale' => 'ar', 'name' => 'Sri Lanka',),
            array('country_id' => '204', 'locale' => 'en', 'name' => 'St. Helena',),
            array('country_id' => '204', 'locale' => 'ar', 'name' => 'St. Helena',),
            array('country_id' => '205', 'locale' => 'en', 'name' => 'St. Pierre and Miquelon',),
            array('country_id' => '205', 'locale' => 'ar', 'name' => 'St. Pierre and Miquelon',),
            array('country_id' => '206', 'locale' => 'en', 'name' => 'Sudan',),
            array('country_id' => '206', 'locale' => 'ar', 'name' => 'Sudan',),
            array('country_id' => '207', 'locale' => 'en', 'name' => 'Suriname',),
            array('country_id' => '207', 'locale' => 'ar', 'name' => 'Suriname',),
            array('country_id' => '208', 'locale' => 'en', 'name' => 'Svalbard and Jan Mayen Islands',),
            array('country_id' => '208', 'locale' => 'ar', 'name' => 'Svalbard and Jan Mayen Islands',),
            array('country_id' => '209', 'locale' => 'en', 'name' => 'Swaziland',),
            array('country_id' => '209', 'locale' => 'ar', 'name' => 'Swaziland',),
            array('country_id' => '210', 'locale' => 'en', 'name' => 'Sweden',),
            array('country_id' => '210', 'locale' => 'ar', 'name' => 'Sweden',),
            array('country_id' => '211', 'locale' => 'en', 'name' => 'Switzerland',),
            array('country_id' => '211', 'locale' => 'ar', 'name' => 'Switzerland',),
            array('country_id' => '212', 'locale' => 'en', 'name' => 'Syrian Arab Republic',),
            array('country_id' => '212', 'locale' => 'ar', 'name' => 'Syrian Arab Republic',),
            array('country_id' => '213', 'locale' => 'en', 'name' => 'Taiwan',),
            array('country_id' => '213', 'locale' => 'ar', 'name' => 'Taiwan',),
            array('country_id' => '214', 'locale' => 'en', 'name' => 'Tajikistan',),
            array('country_id' => '214', 'locale' => 'ar', 'name' => 'Tajikistan',),
            array('country_id' => '215', 'locale' => 'en', 'name' => 'United Republic of Tanzania',),
            array('country_id' => '215', 'locale' => 'ar', 'name' => 'United Republic of Tanzania',),
            array('country_id' => '216', 'locale' => 'en', 'name' => 'Thailand',),
            array('country_id' => '216', 'locale' => 'ar', 'name' => 'Thailand',),
            array('country_id' => '217', 'locale' => 'en', 'name' => 'Togo',),
            array('country_id' => '217', 'locale' => 'ar', 'name' => 'Togo',),
            array('country_id' => '218', 'locale' => 'en', 'name' => 'Tokelau',),
            array('country_id' => '218', 'locale' => 'ar', 'name' => 'Tokelau',),
            array('country_id' => '219', 'locale' => 'en', 'name' => 'Tonga',),
            array('country_id' => '219', 'locale' => 'ar', 'name' => 'Tonga',),
            array('country_id' => '220', 'locale' => 'en', 'name' => 'Trinidad and Tobago',),
            array('country_id' => '220', 'locale' => 'ar', 'name' => 'Trinidad and Tobago',),
            array('country_id' => '221', 'locale' => 'en', 'name' => 'Tunisia',),
            array('country_id' => '221', 'locale' => 'ar', 'name' => 'Tunisia',),
            array('country_id' => '222', 'locale' => 'en', 'name' => 'Turkey',),
            array('country_id' => '222', 'locale' => 'ar', 'name' => 'Turkey',),
            array('country_id' => '223', 'locale' => 'en', 'name' => 'Turkmenistan',),
            array('country_id' => '223', 'locale' => 'ar', 'name' => 'Turkmenistan',),
            array('country_id' => '224', 'locale' => 'en', 'name' => 'Turks and Caicos Islands',),
            array('country_id' => '224', 'locale' => 'ar', 'name' => 'Turks and Caicos Islands',),
            array('country_id' => '225', 'locale' => 'en', 'name' => 'Tuvalu',),
            array('country_id' => '225', 'locale' => 'ar', 'name' => 'Tuvalu',),
            array('country_id' => '226', 'locale' => 'en', 'name' => 'Uganda',),
            array('country_id' => '226', 'locale' => 'ar', 'name' => 'Uganda',),
            array('country_id' => '227', 'locale' => 'en', 'name' => 'Ukraine',),
            array('country_id' => '227', 'locale' => 'ar', 'name' => 'Ukraine',),
            array('country_id' => '228', 'locale' => 'en', 'name' => 'United Arab Emirates',),
            array('country_id' => '228', 'locale' => 'ar', 'name' => 'United Arab Emirates',),
            array('country_id' => '229', 'locale' => 'en', 'name' => 'United Kingdom',),
            array('country_id' => '229', 'locale' => 'ar', 'name' => 'United Kingdom',),
            array('country_id' => '230', 'locale' => 'en', 'name' => 'United States',),
            array('country_id' => '230', 'locale' => 'ar', 'name' => 'United States',),
            array('country_id' => '231', 'locale' => 'en', 'name' => 'United States minor outlying islands',),
            array('country_id' => '231', 'locale' => 'ar', 'name' => 'United States minor outlying islands',),
            array('country_id' => '232', 'locale' => 'en', 'name' => 'Uruguay',),
            array('country_id' => '232', 'locale' => 'ar', 'name' => 'Uruguay',),
            array('country_id' => '233', 'locale' => 'en', 'name' => 'Uzbekistan',),
            array('country_id' => '233', 'locale' => 'ar', 'name' => 'Uzbekistan',),
            array('country_id' => '234', 'locale' => 'en', 'name' => 'Vanuatu',),
            array('country_id' => '234', 'locale' => 'ar', 'name' => 'Vanuatu',),
            array('country_id' => '235', 'locale' => 'en', 'name' => 'Vatican City State',),
            array('country_id' => '235', 'locale' => 'ar', 'name' => 'Vatican City State',),
            array('country_id' => '236', 'locale' => 'en', 'name' => 'Venezuela',),
            array('country_id' => '236', 'locale' => 'ar', 'name' => 'Venezuela',),
            array('country_id' => '237', 'locale' => 'en', 'name' => 'Vietnam',),
            array('country_id' => '237', 'locale' => 'ar', 'name' => 'Vietnam',),
            array('country_id' => '238', 'locale' => 'en', 'name' => 'Virgin Islands (British)',),
            array('country_id' => '238', 'locale' => 'ar', 'name' => 'Virgin Islands (British)',),
            array('country_id' => '239', 'locale' => 'en', 'name' => 'Virgin Islands (U.S.)',),
            array('country_id' => '239', 'locale' => 'ar', 'name' => 'Virgin Islands (U.S.)',),
            array('country_id' => '240', 'locale' => 'en', 'name' => 'Wallis and Futuna Islands',),
            array('country_id' => '240', 'locale' => 'ar', 'name' => 'Wallis and Futuna Islands',),
            array('country_id' => '241', 'locale' => 'en', 'name' => 'Western Sahara',),
            array('country_id' => '241', 'locale' => 'ar', 'name' => 'Western Sahara',),
            array('country_id' => '242', 'locale' => 'en', 'name' => 'Yemen',),
            array('country_id' => '242', 'locale' => 'ar', 'name' => 'Yemen',),
            array('country_id' => '243', 'locale' => 'en', 'name' => 'Zaire',),
            array('country_id' => '243', 'locale' => 'ar', 'name' => 'Zaire',),
            array('country_id' => '244', 'locale' => 'en', 'name' => 'Zambia',),
            array('country_id' => '244', 'locale' => 'ar', 'name' => 'Zambia',),
            array('country_id' => '245', 'locale' => 'en', 'name' => 'Zimbabwe',),
            array('country_id' => '245', 'locale' => 'ar', 'name' => 'Zimbabwe',),
        ];
        CountryTranslation::insert($countriesTranslations);
    }
}
